# Generated by Django 4.2 on 2023-04-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.menu')),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
            ],
        ),
    ]
